language: ruby
rvm:
<<<<<<< HEAD
  - "2.1.0"
=======
  - "1.9.3-p448"
  - "2.0.0-p247"
>>>>>>> Reducing history complexity to merge rails 4 update

script: bundle exec rspec spec

before_script:
  - mysql -e 'create database pull_req_test;'
  - cp config/database_example.yml config/database.yml
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
