## GitHub
github:
  client_id: 1234
  client_secret: f00b4rq4zq4t

subdomain1:
  client_id: 5678
  client_secret: f55b6rq7zq8t
  client_options:
    site: 'http://git.subdomain1.com/'
    api_url: 'http://git.subdomain1.com/api/v3'
    authorize_url: 'http://git.subdomain1.com/login/oauth/authorize'
    token_url: 'http://git.subdomain1.com/login/oauth/access_token'

subdomain2:
  client_id: 9012
  client_secret: f99b0rq1zq2t
  client_options:
    site: 'http://git.subdomain2.com/'
    api_url: 'http://git.subdomain2.com/api/v3'
    authorize_url: 'http://git.subdomain2.com/login/oauth/authorize'
    token_url: 'http://git.subdomain2.com/login/oauth/access_token'
