client_id: 1234
client_secret: f00b4rq4zq4t
client_options:
  site: 'http://git.my_awesome_domain.com/api/v3'
  authorize_url: 'http://git.my_awesome_domain.com/login/oauth/authorize'
  token_url: 'http://git.my_awesome_domain.com/login/oauth/access_token'